name: valida-dependencias
on:
  workflow_call:
    inputs:
      tipo-projeto:
        description: 'Tipo do projeto que está utilizando a action (API, BFF, MFE)'
        required: true
        type: string
      diretorio-sln:
        description: 'Diretorio onde está o arquivo .sln'
        required: true
        type: string
    secrets:  # Permite o uso de secrets do repositório chamador, caso necessário
      GH_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout do repositório chamador para obter o caminho dele
    - name: Checkout caller repository
      uses: actions/checkout@v4
      with:
        path: caller-repo

    - name: Checkout reusable workflow repository
      uses: actions/checkout@v4
      with:
        repository: brunoritter123/workflows
        token: ${{ secrets.GH_TOKEN }}  # Autenticação para acessar o repositório do workflow reutilizável
        path: reusable-repo

    - name: Teste Input tipo-projeto
      run: echo tipo-projeto ${{inputs.tipo-projeto}}

    - name: Teste Input diretorio-sln
      run: echo diretorio-sln ${{inputs.diretorio-sln}}

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore
      working-directory: ${{inputs.diretorio-sln}}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Lista arquivos
      run: ls

    - name: Run validation script
      run: python reusable-repo/valida_dependencias.py --path_projeto caller-repo/${{inputs.diretorio-sln}} --tipo_projeto ${{inputs.diretorio-sln}}
      working-directory: ${{inputs.diretorio-sln}}
