name: valida-dependencias
on:
  workflow_call:
    inputs:
      tipo-projeto:
        description: 'Tipo do projeto que está utilizando a action (API, BFF, MFE)'
        required: true
        type: string
      diretorio-sln:
        description: 'Diretorio onde está o arquivo .sln'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore
      working-directory: ${{inputs.diretorio-sln}}

    - name: Teste Input tipo-projeto
      run: echo tipo-projeto ${{inputs.tipo-projeto}}

    - name: Teste Input diretorio-sln
      run: echo diretorio-sln ${{inputs.diretorio-sln}}
